name: 'Update Types (weekly)'
on:
  schedule:
    - cron: '0 0 * * 0'

env:
  GIT_USERNAME: ${{secrets.GIT_USERNAME}}
  GIT_EMAIL: ${{secrets.GIT_EMAIL}}
  GH_APP_ACCESS_TOKEN: ${{secrets.GH_APP_ACCESS_TOKEN}}

jobs:
  base:
    name: Update Base Types
    environment: "Type Updating"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: base
  gtk3:
    name: Update GTK3 Types
    environment: "Type Updating"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: gtk3
  gtk4:
    name: Update GTK4 Types
    environment: "Type Updating"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: gtk4
  shell8:
    name: Update Shell (8) Types
    environment: "Type Updating"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: shell8