name: 'Update Types workflow'
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Update Types (weekly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types