name: 'Update Types (manually)'
on:
  workflow_dispatch:
    inputs:
      set-to-build:
        description: 'Set to build'
        required: true
        default: 'base'

env:
  GIT_USERNAME: ${{secrets.GIT_USERNAME}}
  GIT_EMAIL: ${{secrets.GIT_EMAIL}}
  GH_APP_ACCESS_TOKEN: ${{secrets.GH_APP_ACCESS_TOKEN}}

jobs:
  base:
    name: Update Types
    environment: "Type Updating" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: "${{ github.event.inputs.set-to-build }}"
