name: 'Update Types (manually)'
on:
  workflow_dispatch:
    inputs:
      set-to-build:
        description: 'Set to build'
        required: true
        default: 'base'

jobs:
  base:
    name: Update Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/update-types
        with:
           set-to-build: "${{ github.event.inputs.set-to-build }}"
